name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check HTML File
        run: test -f index.html

      - name: Build Application
        run: |
          mkdir build
          cp index.html build/

      - name: Run Tests
        run: |
          test -f build/index.html
          grep -q "CI/CD Pipeline" build/index.html

      - name: Upload Build
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
